version: '3.9'

services:
  dash_ml:
    command: tail -f /dev/null
    image: bakytur/a3-ml-dash:v01
    platform: linux/x86_64
    build: 
      context: .
      dockerfile: .Dockerfile
    ports:
      - 9001:80
    volumes:
      - ./code:/root/code
      - vscode-server:/root/.vscode-server
    environment:
      - HOST=0.0.0.0
      - PORT=80
    env_file:
      - .env      
volumes:
  vscode-server:      